### PR TITLE
feat: add basic animation

### PR DESCRIPTION
**Pull request by juancarlosfarah**
Here's a very basic, but promising approach using React Spring.

### CODE REVIEW

**Comment by juancarlosfarah** [comment]
Relates to #4

**Review by pyphilia — APPROVED** [review]
Nice! I'll try to find a way to make it wave...

**Comment by juancarlosfarah** [comment]
@pyphilia, shall I go ahead and merge this?

**Comment by juancarlosfarah** [comment]
@pyphilia, what should we do with this branch?

**Comment by juancarlosfarah** [comment]
Closing in favour of #6.

**Pull request closed without merging**
