### PR TITLE
54/actions

### PR DESCRIPTION
**Pull request by hagoptaminian**
@juancarlosfarah please have a look at this example action dispatch! I'm marking this as a draft PR because I just made it to get your feedback.

- Am I missing anything in terms of how to dispatch actions?
- In `src/actions/action.js` in `graasp-app-submit-answer` ([link](https://github.com/graasp/graasp-app-submit-answer/blob/46b6e897b305d7b26a85afb4af6ac12853f00087/src/actions/action.js)), you remove following code from the function `postAction`:

```
// if analytics is not turned on, abort
// todo: post message analytics + ensure that desktop keeps analytics
if (!analytics) {
    return false;
}
```

I kept it in the equivalent function in this app, but let me know if there's a reason to remove it.

### CODE REVIEW

**Comment by hagoptaminian** [comment]
(@juancarlosfarah slight mix up with the branches... relevant code for the actions commit are the `onClickPlay` function in `AnimationControls.js` and the verbs in `src/config/verbs.js`)

**Review by pyphilia — APPROVED** [review]
For me everything is okay, but I'll let JC check it out.

**Comment by juancarlosfarah** [comment]
> @juancarlosfarah please have a look at this example action dispatch! I'm marking this as a draft PR because I just made it to get your feedback.
> 
> * Am I missing anything in terms of how to dispatch actions?
> * In `src/actions/action.js` in `graasp-app-submit-answer` ([link](https://github.com/graasp/graasp-app-submit-answer/blob/46b6e897b305d7b26a85afb4af6ac12853f00087/src/actions/action.js)), you remove following code from the function `postAction`:
> 
> ```
> // if analytics is not turned on, abort
> // todo: post message analytics + ensure that desktop keeps analytics
> if (!analytics) {
>     return false;
> }
> ```
> 
> I kept it in the equivalent function in this app, but let me know if there's a reason to remove it.

Did I remove it or was it never there?

**Review by juancarlosfarah — APPROVED** [review]
🕺

**Review by juancarlosfarah — APPROVED** [review]
💪

**Pull request merged**
