### PR TITLE
feat: implement basic acceleration

### LINKED ISSUE #11: simulate charge acceleration

### PR DESCRIPTION
**Pull request by juancarlosfarah**
closes #11

### CODE REVIEW

**Comment by juancarlosfarah** [comment]
@pyphilia, @hagoptaminian, please have a look. I've implemented a basic acceleration function. I've also simplified the drawing of the lines using angles. The app is starting to look nice.

**Comment by juancarlosfarah** [comment]
image

**Review by pyphilia — APPROVED** [review]
It is all good for me. The lines are satisfactorily moving! I hovewer got strange behaviour, but I guess it will be rectified when the actual physical function will be used:
- When oscillation is turned on with an amplitude of 0, the charge is moving really softly. I would expect it to not move and be the equivalent to no oscillation.
- If I change the amplitude from a big value (250) to a small value (0) when the charge is far from its initial position, the charge will slowly slowly return to its initial position before applying the small value. I am not sure why this behaviour is happening.

**Comment by juancarlosfarah** [comment]
Changes included and improved upon in #13.

**Pull request closed without merging**
